CREATE TABLE IF NOT EXISTS `mytable` (

`_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
